import 'package:flutter/material.dart';

class GuideScreen extends StatelessWidget {
  const GuideScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('使い方ガイド')),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: const [
            Text('ホーム画面',
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
            SizedBox(height: 8),
            Text('• 上部 AppBar の検索ボタン（ラベル付き大型ボタン）から横断検索が可能'),
            Text('• 右上の設定アイコンから詳細設定 / 翻訳キャッシュクリアなどが行えます'),
            Text(
                '• タブ: ニュース / 国別 / Markets / お気に入り / コメント / タイムカプセル / Wikipedia'),
            Text('• ニュース一覧は下方向スクロールで自動的に続きをロード（無限スクロール）'),
            Text('• 下にスワイプして離すと最新情報を再取得（プルダウン更新）'),
            Text('• 600px 以上スクロールすると右下にページトップへ戻るボタンが出現（上スクロール時のみ表示）'),
            SizedBox(height: 12),
            Text('Markets タブ（マーケット情報）',
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
            SizedBox(height: 8),
            Text(
                '• USD/JPY, BTC/JPY, ETH/JPY など主要通貨・仮想通貨の最新レートとスパークラインチャートを表示'),
            Text('• チャートは過去60ポイントの推移を視覚化（グラデーション塗り+終点マーカー付き）'),
            Text('• 各カードに変動率（%）、高値・安値、変化方向（▲▼→）を表示'),
            Text('• 20秒ごとに自動更新、タップで手動更新も可能'),
            Text(
                '• データソース: 為替は Alpha Vantage/Twelve Data/exchangerate.host/open.er-api.com、仮想通貨は CoinGecko API（無料）'),
            SizedBox(height: 12),
            Text('国別ニュース',
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
            SizedBox(height: 8),
            Text('• 国カードをタップすると該当国の最新ニュース一覧を表示'),
            Text('• 重要そうな国を上部 10 カ国でクイックアクセス'),
            Text('• 画面上部にティッカー表示（USD/JPY, BTC/JPY など主要レート）'),
            Text('• ティッカーは2分ごとに自動更新、タップで即座に手動更新も可能'),
            Text('• ティッカーカードは変化方向に応じて色付き矢印（▲▼→）を表示'),
            SizedBox(height: 12),
            Text('アニメーション・UI機能',
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
            SizedBox(height: 8),
            Text('• 背景アニメーション: 約10秒周期でリニアグラデーションが微細にシフト（お気に入り、コメント、タイムカプセル画面）'),
            Text('• ニュースカード登場時に opacity + Y-slide アニメーション（下から浮き上がるエフェクト）'),
            Text('• ティッカー更新時は fade + Y-slide トランジションで変化を強調'),
            Text('• マウスホバー時のカード拡大・影変化（設定で ON/OFF 可能）'),
            SizedBox(height: 12),
            Text('Wikipedia タブ',
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
            SizedBox(height: 8),
            Text('• 単語や人物名を入力すると日本語 Wikipedia から要約を取得します'),
            Text('• 入力中に候補が最大5件表示されタップで反映'),
            Text('• 「検索」ボタンで下部に要約が表示され、全文表示を開くボタンも利用可能'),
            Text('• 過去の検索語は自動的に履歴へ保存され設定画面から一覧可能'),
            SizedBox(height: 12),
            Text('記事詳細での Wikipedia 連携',
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
            SizedBox(height: 8),
            Text('• 記事本文中の英単語を選択 → コンテキストメニューから Wikipedia 検索'),
            Text('• 取得した要約は下部シートに表示され、全文リンクも利用可能'),
            Text('• 検索した語は履歴へ保存され後から再検索可能'),
            SizedBox(height: 12),
            Text('コメント',
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
            SizedBox(height: 8),
            Text('• 記事詳細画面で引用＋コメントを追加すると「コメント」タブに一覧表示'),
            Text('• 各コメントカード右上のメニューから編集 / 削除 / 全削除が可能'),
            SizedBox(height: 12),
            Text('オフライン / エラー対応',
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
            SizedBox(height: 8),
            Text('• 通信失敗時はトレンド画面上部に赤いエラーバナーが表示されます'),
            Text('• 過去に取得した記事があればキャッシュから自動復元し閲覧可能'),
            Text('• Web 版では未対応プラグインを避けるため簡易ストレージで記事を保持'),
            Text('• 為替レートはキャッシュに保存され、API失敗時でも最後に成功した値を表示'),
            SizedBox(height: 12),
            Text('翻訳',
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
            SizedBox(height: 8),
            Text('• 自動翻訳が ON の場合、記事表示時に説明文またはタイトルを即座に翻訳'),
            Text('• DeepL 優先設定が ON でキー有効時は高品質翻訳を優先（失敗時は簡易辞書）'),
            Text('• 「翻訳済み」チップは簡易翻訳では表示されません'),
            SizedBox(height: 12),
            Text('便利な機能',
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
            SizedBox(height: 8),
            Text('• お気に入り登録 / 翻訳キャッシュクリア'),
            Text('• コメント引用保存 / タイムカプセル日時指定保存'),
            Text('• ダークモード / ホバー拡張 / 画像オーバーレイ表示モード'),
            Text('• トレンド一覧では重要度ラベル＋ムード指標を確認可能'),
            Text('• マーケットデータは自動更新され、タップで即座に最新値を取得'),
          ],
        ),
      ),
    );
  }
}
