import 'package:flutter/material.dart';

class GuideScreen extends StatelessWidget {
  const GuideScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('使い方ガイド')),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text('📱 ホーム画面',
                style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 8),
            const Text('• 上部 AppBar の検索ボタン（ラベル付き大型ボタン）から横断検索が可能'),
            const Text('• 右上の設定アイコンから詳細設定 / 翻訳キャッシュクリアなどが行えます'),
            const Text(
                '• タブ: ニュース / トレンド / 国別 / 地図 / Markets / お気に入り / コメント / タイムカプセル / Wikipedia / 会員登録 など'),
            const Text('• ニュース一覧は下方向スクロールで自動的に続きをロード（無限スクロール）'),
            const Text('• 下にスワイプして離すと最新情報を再取得（プルダウン更新）'),
            const Text('• 600px 以上スクロールすると右下にページトップへ戻るボタンが出現'),
            const SizedBox(height: 16),
            const Text('🔐 会員登録・ログイン',
                style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 8),
            const Text('• 会員登録タブからメールアドレス、表示名、パスワードでアカウント作成'),
            const Text('• パスワードは暗号化して保存されるため安全です（SHA256+salt方式）'),
            const Text('• Web版とアプリ版で自動的に最適なストレージ方式を選択'),
            const Text('• 一度登録すると次回起動時に自動ログイン'),
            const Text('• ログイン機能は実装済み（UI追加予定）'),
            const SizedBox(height: 16),
            const Text('🌍 地図ニュース',
                style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 8),
            const Text('• 世界地図上に主要地域のニュースカードを配置'),
            const Text('• カード右上のバッジに現在のニュース件数を表示（1分キャッシュ）'),
            const Text('• 地域カードをタップすると該当国の詳細ニュース一覧へ'),
            const Text('• アメリカ、イギリス、日本、中国、インド、ブラジルなど対応'),
            const SizedBox(height: 16),
            const Text('📊 Markets タブ（マーケット情報）',
                style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 8),
            const Text(
                '• USD/JPY, BTC/JPY, ETH/JPY など主要通貨・仮想通貨の最新レートとスパークラインチャートを表示'),
            const Text('• チャートは過去60ポイントの推移を視覚化（グラデーション塗り+終点マーカー付き）'),
            const Text('• 各カードに変動率（%）、高値・安値、変化方向（▲▼→）を表示'),
            const Text('• 20秒ごとに自動更新、タップで手動更新も可能'),
            const Text(
                '• データソース: 為替は Alpha Vantage/Twelve Data/exchangerate.host/open.er-api.com、仮想通貨は CoinGecko API（無料）'),
            const SizedBox(height: 16),
            const Text('🗺️ 国別ニュース',
                style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 8),
            const Text('• 国カードをタップすると該当国の最新ニュース一覧を表示'),
            const Text('• 重要そうな国を上部 10 カ国でクイックアクセス'),
            const Text('• 画面上部にティッカー表示（USD/JPY, BTC/JPY など主要レート）'),
            const Text('• ティッカーは2分ごとに自動更新、タップで即座に手動更新も可能'),
            const Text('• ティッカーカードは変化方向に応じて色付き矢印（▲▼→）を表示'),
            const SizedBox(height: 16),
            const Text('⚠️ API制限とエラー対応',
                style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 8),
            const Text(
                '• ニュースAPIは3つのプロバイダー（GNews, Currents, MediaStack）を自動フォールバック'),
            const Text('• レート制限（429エラー）発生時は10分間該当プロバイダーをスキップ'),
            const Text('• 全API制限中は画面上部に赤いエラーバナーが表示されます'),
            const Text('• 通信失敗時は過去に取得した記事をキャッシュから自動復元'),
            const Text('• Web版では未対応プラグインを避けるため簡易ストレージで記事を保持'),
            const Text('• 為替レートはキャッシュに保存され、API失敗時でも最後の成功値を表示'),
            const SizedBox(height: 16),
            const Text('🎨 アニメーション・UI機能',
                style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 8),
            const Text(
                '• 背景アニメーション: 約10秒周期でリニアグラデーションが微細にシフト（お気に入り、コメント、タイムカプセル画面）'),
            const Text(
                '• ニュースカード登場時に opacity + Y-slide アニメーション（下から浮き上がるエフェクト）'),
            const Text('• ティッカー更新時は fade + Y-slide トランジションで変化を強調'),
            const Text('• マウスホバー時のカード拡大・影変化（設定で ON/OFF 可能）'),
            const Text('• ヘッダー透明度を調整し背景と文字の重なりを防止'),
            const Text('• 速報バナーは画面上部に固定表示（スクロールしても常に見える）'),
            const SizedBox(height: 16),
            const Text('📚 Wikipedia タブ',
                style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 8),
            const Text('• 単語や人物名を入力すると日本語 Wikipedia から要約を取得します'),
            const Text('• 入力中に候補が最大5件表示されタップで反映'),
            const Text('• 「検索」ボタンで下部に要約が表示され、全文表示を開くボタンも利用可能'),
            const Text('• 過去の検索語は自動的に履歴へ保存され設定画面から一覧可能'),
            const SizedBox(height: 16),
            const Text('🔍 記事詳細での Wikipedia 連携',
                style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 8),
            const Text('• 記事本文中の英単語を選択 → コンテキストメニューから Wikipedia 検索'),
            const Text('• 取得した要約は下部シートに表示され、全文リンクも利用可能'),
            const Text('• 検索した語は履歴へ保存され後から再検索可能'),
            const SizedBox(height: 16),
            const Text('💬 コメント',
                style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 8),
            const Text('• 記事詳細画面で引用＋コメントを追加すると「コメント」タブに一覧表示'),
            const Text('• 各コメントカード右上のメニューから編集 / 削除 / 全削除が可能'),
            const SizedBox(height: 16),
            const Text('🌐 翻訳',
                style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 8),
            const Text('• 自動翻訳が ON の場合、記事表示時に説明文またはタイトルを即座に翻訳'),
            const Text('• DeepL 優先設定が ON でキー有効時は高品質翻訳を優先（失敗時は簡易辞書）'),
            const Text('• 簡易辞書は約800語対応、複数形や大文字小文字も自動変換'),
            const Text('• 「翻訳済み」チップは簡易翻訳では表示されません'),
            const Text('• 翻訳結果はセッション中メモリキャッシュされ、設定画面から手動クリア可能'),
            const SizedBox(height: 16),
            const Text('⚙️ 便利な機能',
                style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 8),
            const Text('• お気に入り登録 / 翻訳キャッシュクリア'),
            const Text('• コメント引用保存 / タイムカプセル日時指定保存'),
            const Text('• ダークモード / ホバー拡張 / 画像オーバーレイ表示モード'),
            const Text('• トレンド一覧では重要度ラベル＋ムード指標を確認可能'),
            const Text('• マーケットデータは自動更新され、タップで即座に最新値を取得'),
            const SizedBox(height: 16),
            const Text('🔧 開発者向け情報',
                style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
            const SizedBox(height: 8),
            const Text('• 詳細なアーキテクチャと実装詳細は README.md を参照'),
            const Text('• Services層でビジネスロジック、Screens/Widgetsで表示を分離'),
            const Text('• Web/ネイティブの自動分岐により両環境で動作'),
            const Text('• レート制限、キャッシュ、ログ抑制などパフォーマンス最適化済み'),
          ],
        ),
      ),
    );
  }
}
