import 'package:flutter/material.dart';

class GuideScreen extends StatelessWidget {
  const GuideScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('使い方ガイド')),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: const [
            Text('ホーム画面',
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
            SizedBox(height: 8),
            Text('• 上部 AppBar の検索アイコンから横断検索が可能'),
            Text('• 右上の設定アイコンから詳細設定 / 翻訳キャッシュクリアなどが行えます'),
            Text('• タブ: ニュース / 国別 / 天気 / お気に入り / コメント / タイムカプセル / Wikipedia'),
            Text('• ニュース一覧は下方向スクロールで自動的に続きをロード（無限スクロール）'),
            Text('• 下にスワイプして離すと最新情報を再取得（プルダウン更新）'),
            SizedBox(height: 12),
            Text('Wikipedia タブ',
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
            SizedBox(height: 8),
            Text('• 単語や人物名を入力すると日本語 Wikipedia から要約を取得します'),
            Text('• 入力中に候補が最大5件表示されタップで反映'),
            Text('• 「検索」ボタンで下部に要約が表示され、全文表示を開くボタンも利用可能'),
            Text('• 過去の検索語は自動的に履歴へ保存され設定画面から一覧可能'),
            SizedBox(height: 12),
            Text('記事詳細での Wikipedia 連携',
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
            SizedBox(height: 8),
            Text('• 記事本文中の英単語を選択 → コンテキストメニューから Wikipedia 検索'),
            Text('• 取得した要約は下部シートに表示され、全文リンクも利用可能'),
            Text('• 検索した語は履歴へ保存され後から再検索可能'),
            SizedBox(height: 12),
            Text('コメント',
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
            SizedBox(height: 8),
            Text('• 記事詳細画面で引用＋コメントを追加すると「コメント」タブに一覧表示'),
            Text('• 各コメントカード右上のメニューから編集 / 削除 / 全削除が可能'),
            SizedBox(height: 12),
            Text('オフライン / エラー対応',
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
            SizedBox(height: 8),
            Text('• 通信失敗時はトレンド画面上部に赤いエラーバナーが表示されます'),
            Text('• 過去に取得した記事があればキャッシュから自動復元し閲覧可能'),
            Text('• Web 版では未対応プラグインを避けるため簡易ストレージで記事を保持'),
            SizedBox(height: 12),
            Text('翻訳',
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
            SizedBox(height: 8),
            Text('• 自動翻訳が ON の場合、記事表示時に説明文またはタイトルを即座に翻訳'),
            Text('• DeepL 優先設定が ON でキー有効時は高品質翻訳を優先（失敗時は簡易辞書）'),
            Text('• 「翻訳済み」チップは簡易翻訳では表示されません'),
            SizedBox(height: 12),
            Text('国別ニュース',
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
            SizedBox(height: 8),
            Text('• 国カードをタップすると該当国の最新ニュース一覧を表示'),
            Text('• 重要そうな国を上部 10 カ国でクイックアクセス'),
            SizedBox(height: 12),
            Text('便利な機能',
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
            SizedBox(height: 8),
            Text('• お気に入り登録 / 翻訳キャッシュクリア'),
            Text('• コメント引用保存 / タイムカプセル日時指定保存'),
            Text('• ダークモード / ホバー拡張 / 画像オーバーレイ表示モード'),
            Text('• トレンド一覧では重要度ラベル＋ムード指標を確認可能'),
          ],
        ),
      ),
    );
  }
}
